"""add status to site_transfer

Revision ID: ef509da9333c
Revises: 'a00aeb045709'
Create Date: 2026-07-31 05:21:43.255827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef509da9333c'
down_revision: Union[str, None] = 'a00aeb045709'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_transfers', sa.Column('status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_transfers', 'status')
    # ### end Alembic commands ###
